# Generated by Django 5.0.6 on 2024-06-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_menucat_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='category_id',
            new_name='categ_id',
        ),
    ]
