# Generated by Django 5.0.6 on 2024-06-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_category_id_menu_categ_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='categ_id',
            field=models.CharField(max_length=40),
        ),
    ]
