# Generated by Django 5.0.6 on 2024-06-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_menu_categ_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='categ_id',
            field=models.IntegerField(choices=[(1, 'indian'), (2, 'French'), (3, 'Roman'), (4, 'Greek')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default='0'),
        ),
    ]
